services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "test_pass"
      POSTGRES_DB: "test_db"
    ports:
      - '5432:5432'
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      POSTGRESQL_DB_USER: "test_user"
      POSTGRESQL_DB_PASSWORD: "test_pass"
      POSTGRESQL_DB_NAME: "test_db"
      POSTGRESQL_DB_HOST: "db"
      POSTGRESQL_DB_PORT: "5432"
    depends_on:
      - db
